# Generated by Django 5.0.1 on 2024-02-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='messege',
            field=models.TextField(max_length=5000),
        ),
    ]
